### ISSUE TITLE
needed improve documentation for newbie developers (add quick start to readme)

### ISSUE THREAD

**Issue by NTMan** [JumpFm/jumpfm#11]
```
$ git clone git@github.com:Gilad-Kutiel-App/jumpfm.git
$ cd jumpfm
$ npm install
$ npm install electron
$ ./node_modules/.bin/electron .
```
Actual result:
![screenshot from 2017-08-24 21-30-38](https://user-images.githubusercontent.com/200750/29677331-3e37e3ac-8914-11e7-8038-5f66d719c601.png)

What I am doing wrong?

**Comment by gkutiel** [comment]
Made [some](https://github.com/Gilad-Kutiel-App/jumpfm), please confirm that it works out for you.

**Comment by NTMan** [comment]
Thanks, it really helps easy involved in development.

Some remarks:
1) For installing npm packages globally must used root rights for this needed add ```sudo``` before line:
``` npm i -g typescript```
```sudo npm i -g typescript // is right variant for Linux```

2) ```electron .```
I see that you use globally installed electron, for this I propose change command line from remark 1 to follow variant:
```sudo npm i -g typescript electron```
But in my distribution, I have errors during global install electron
```
$ sudo npm i -g electron
[sudo] password for mikhail: 
/usr/bin/electron -> /usr/lib/node_modules/electron/cli.js

> electron@1.7.5 postinstall /usr/lib/node_modules/electron
> node install.js

/usr/lib/node_modules/electron/install.js:48
  throw err
  ^

Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/electron/.electron'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.7.5 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.7.5 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-08-26T20_32_31_504Z-debug.log
```
I think it bug in electron package
instead of ```mkdir '/usr/lib/node_modules/electron/.electron'``` they should use ```mkdir -p' /usr/lib/ node_modules/electron/.electron'```
For example:
```
# mkdir '/usr/lib/node_modules/electron/.electron'
mkdir: can not create directory '/usr/lib/node_modules/electron/.electron': No such file or directory
# mkdir -p '/usr/lib/node_modules/electron/.electron'
```
Until this bug not fixed I'm forced to install electron locally and launch jumpfm with command
```$ ./node_modules/.bin/electron .```

3) How much time ```tsc -w``` working ???
```
$ tsc -w
1:40:32 AM - Compilation complete. Watching for file changes.


```
I am waiting several minutes for the exit of this command, but not having waited completion and exit in terminal,  terminate it by Ctrl + C.
Jumpfm works despite this, but it left me with unpleasant after-taste.

**Comment by gkutiel** [comment]
I updated the README.

1. You might want to [change npm's default directory](https://docs.npmjs.com/getting-started/fixing-npm-permissions#option-2-change-npms-default-directory-to-another-directory)
2. Use different terminal for each of  ```tsc -w```, ```sass --watch scss:css```, ```electron .``` these commands don't return until you kill them.

**Comment by NTMan** [comment]
Thanks, I am also would added warning note:
Due the electron an unsupport installation under root, don't  use sudo, change owner of node_modules instead ```sudo chown -vR `whoami` `npm get prefix`/lib/node_modules/``` or change prefix to home dir ``` mkdir ~/npm-global && npm config set prefix ~/npm-global/```

Also would be nice have helpers for develop plugins in git. I means that all plugins automatically downloaded as npm modules to directory ```~/.jumpfm/plugins/node_modules```
For example  I want make some changes to jumpfm-fs plugin for eliminate annoying Panel updates when changed some files. And I needed manually symlink ```~/.jumpfm/plugins/node_modules/jumpfm-fs``` to repo ```https://github.com/JumpFm/jumpfm-fs``` which I need clone separately. And use separate copy of ```tsc -w``` for plugin. Also I'm constantly afraid that jump-fs will automatically update plugin jumpfm-fs and erase all my uncommitted edits. So it would be very usefull have ability have development version of plugin inside directory plugin inside jumpfm directory. And plugins can be added to this directory with git command.
